version: "3.4"

services:
  db:
    image: postgres:14.1
    restart: "no"
    volumes:
      - ./ais-data.csv:/ais-data.csv:ro
      - ./database/db-init.sql/:/docker-entrypoint-initdb.d/db-init.sql
    container_name: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db