version: "3.4"

services:
  nginx:
    container_name: reverse-proxy
    image: nginx:1.24.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - deno-server
      - react-app
    ports:
      - "7800:7800"

  deno-server:
    container_name: deno-server
    image: deno-server
    build:
      context: ./deno-server
      dockerfile: Dockerfile
    restart: "no"
    expose:
      - 7777
    depends_on:
      - postgres
    env_file:
      - project.env

  postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: "no"
    env_file:
      - project.env
  
  react-app:
    container_name: react-app
    image: react-app
    build:
      context: ./react-app
      dockerfile: Dockerfile
    expose:
      - 80
    depends_on:
      - deno-server