version: "3.4"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - deno-server
    ports:
      - "7800:7800"

  deno-server:
    build: deno-server
    image: deno-server
    restart: "no"
    volumes:
      - ./deno-server/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - db
    env_file:
      - project.env

  db:
    image: postgres:14.1
    restart: "no"
    volumes:
      - ./database/ais-data.csv:/ais-data.csv:ro
      - ./database/db-init.sql/:/docker-entrypoint-initdb.d/db-init.sql
    container_name: postgres
    env_file:
      - project.env
  
  react-app:
    container_name: react-app-dev
    image: react-app-dev
    build:
      context: ./react-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./react-app/:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - deno-server