version: "3.4"

services:
  nginx:
    container_name: reverse-proxy
    image: nginx:1.24.0-alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - deno-server
      - react-app
    ports:
      - "7800:7800"

  deno-server:
    container_name: deno-server-dev
    image: deno-server-dev
    build:
      context: ./deno-server
      dockerfile: Dockerfile.dev
    restart: "no"
    volumes:
      - ./deno-server/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - postgres
    env_file:
      - project.env

  postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: "no"
    env_file:
      - project.env
  
  react-app:
    container_name: react-app-dev
    image: react-app-dev
    build:
      context: ./react-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./react-app/:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - deno-server